### PR TITLE
#40: [Screenshots] Shortcut to paste gifs from Gyazo (closes #40)

### LINKED ISSUE #40: [Screenshots] Shortcut to paste gifs from Gyazo
## requirements
- button to post uploaded gifs from Gyazo
- each user should configure the widget with their own `access_token`
- using gyazo API one can get the last images uploaded on Gyazo

## specs
- add a button in the editor toolbar

image

- should be configurable with user's own access token from Gyazo
  - it should prompt the user an input to add token the first time, and give him chance to delete/update it anytime
  - using `localStorage`
- should check for new user's uploaded gifs
  - user has the option to refresh (force the button to fetch the last uploaded gif)
  - user has the option to acknowledge which image is going to paste (checking date upload or thumbnail)
- clicking it would put the markdown code in the editor
- write a Readme/instructions

### PR DESCRIPTION
**Pull request by francescogior**
Issue #40

- download Gyazo https://gyazo.com/download?dl=now

- sign up and create `access_token` https://gyazo.com/oauth/applications

- set the `access_token`

- Use gyazo to capture a gif screenshot

- Click on the green button ADD GIF

- have fun!

### CODE REVIEW

**Comment by francescogior** [comment]
@FrancescoCioria

**Comment by FrancescoCioria** [comment]
:+1: everything seems to work just fine.

**Comment by FrancescoCioria** [comment]
@francescogior I refactored it to use the `chrome.storage`:
- gets the `accessToken` from the chrome storage
- shows the button only if `accessToken` is not falsy
- the `accessToken` can now be updated using the `popup` (needs some styling...)
image

**Comment by francescogior** [comment]
@FrancescoCioria added  `⇧⌘V` shortcut to paste gifs!
maybe can we merge it now :hammer: :hamster: :koala:

**Pull request merged**
