### PR TITLE
#59: [templates] Distinguish template placeholders from actual content (closes #59)

### LINKED ISSUE #59: make it easier to distinguish template placeholders from actual content
## requirements

Template placeholders are useful, but it's difficult to tell actual content apart from a template placeholder.

Basically I'm proposing this:

| before | after |
| --- | --- |
| image | image |
## specs
- use `quotes` to highlight placeholder paragraphs
- edit regex for autoselect

### PR DESCRIPTION
**Pull request by francescogior**
Issue #59

> asdasd

### CODE REVIEW

**Comment by francescogior** [comment]
commentone!

**Comment by francescogior** [comment]
commentino

**Comment by francescogior** [comment]
commentello

**Comment by francescogior** [comment]
commentozzo

**Comment by francescogior** [comment]
commenteo

**Comment by francescogior** [comment]
commentuff

**Comment by francescogior** [comment]
sadsadas

**Comment by francescogior** [comment]
fadas

**Comment by francescogior** [comment]
non remindare

**Comment by francescogior** [comment]
comm

**Comment by francescogior** [comment]
please no!

**Comment by francescogior** [comment]
sasd

**Comment by francescogior** [comment]
commm

**Comment by francescogior** [comment]
adads

**Comment by francescogior** [comment]
sdfsdfsd

**Comment by francescogior** [comment]
ehiehi

**Comment by francescogior** [comment]
dasdas

**Comment by francescogior** [comment]
dsasadsa

**Comment by francescogior** [comment]
sda

**Comment by francescogior** [comment]
sda

**Comment by francescogior** [comment]
no

**Comment by francescogior** [comment]
`

**Comment by francescogior** [comment]
.

**Comment by FrancescoCioria** [comment]
@francescogior wtf?

**Comment by gabro** [comment]
I think we "solved this" by using markdown quote blocks for placeholders. Right?

**Comment by francescogior** [comment]
Yes, fair enough!

**Pull request closed without merging**
