### PR TITLE
#14: 'New sub-issue' button (closes #14)

### LINKED ISSUE #14: 'New sub-issue' button
Add a 'new sub-issue' button as last item of the right sidebar inside the issue view.

When clicked it will fetch a template and fill it with the parent issue number, using the `parentIssueNo` variable.

### PR DESCRIPTION
**Pull request by gabro**
Issue #14

### CODE REVIEW

**Comment by gabro** [comment]
# Test plan
Install [github-workflow-pal.crx.zip](https://github.com/buildo/github-workflow-pal/files/85971/github-workflow-pal.crx.zip)

- Go to any issue
- Click on `add subissue`
- it should:
  - fetch the template
  - replace the correct parent issue number
  - copy labels from the parent issue, with the exception of the `macro` label
  - copy milestone from the parent issue

**Comment by gabro** [comment]
test comment

**Comment by lucacioria** [comment]
macro is being copied

**Comment by gabro** [comment]
nice catch, fixed.

**Comment by gabro** [comment]
Try this version [github-workflow-pal.crx.zip](https://github.com/buildo/github-workflow-pal/files/86109/github-workflow-pal.crx.zip)

**Pull request merged**
